services:
  movieapp.api:
    image: movieapp.api
    build:
      context: .
      dockerfile: MovieApp.Api/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - DB_SERVER=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=MovieDB
    depends_on:
      - db
    command: ["./wait-for-it.sh", "db:3306", "--", "dotnet", "MovieApp.Api.dll"]
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MovieDB
    ports:
      - "3307:3306"